### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by dtodt** [meteorwebcomponents/synthesis-meteor-polymer-npm-demo#1]
Greetings, thanks for the demo, I like it.

I've wondering how can I bind a meteor collection, to a polymer list element.
I'm not sure if this is the right way, but I'm using mwc:mixin, mwc:router and mwc:layout.

I've something like this:

```
// imports/ui/components/todo-list.js
import {Todo} from "/lib/collections";

Polymer({
    is: "todo-list",
    behaviors: [mwcMixin],
    getMeteorData: function () {
        Meteor.subscribe("todo");

        return {
            todo: Todo.find().fetch()
        };
    }
})
```

```
// imports/ui/components/todo-list.html
<dom-module id="todo-list">
    <template>
        <link rel="stylesheet" href="todo-list.css">
        <template is="dom-repeat" items="[[mwcData.todo]]">
            [[item.title]]
        </template>
    </template>
    <script src="todo-list.js"></script>
</dom-module>
```

```
// imports/startup/client/index.js
import {FlowRouter} from "meteor/kadira:flow-router";
import "/imports/ui";

FlowRouter.wait();

document.addEventListener("WebComponentsReady", function () {
    FlowRouter.initialize({});
});

FlowRouter.route("/", {
    name: 'home',
    action: function (params, queryParams) {
        mwcLayout.render('main-layout', {
            "main": "todo-list"
        });
    }
});
```

```
// client/main.html
<head>
    <title>Todo List</title>
</head>

<body class="fullbleed">
<mwc-layout id="main-layout">
    <div region="main"></div>
</mwc-layout>
</body>
```

```
// lib/collections.js
import {Mongo} from "meteor/mongo";

export const Todo = new Mongo.Collection('todo');
```

**Comment by dtodt** [comment]
I found now this repo:
https://github.com/meteorwebcomponents/polymer-meteor-todo

I'll try with that.

thanks.

**Comment by aruntk** [comment]
@dtod glad to hear you like the mwc project. Regarding https://github.com/meteorwebcomponents/polymer-meteor-todo its not yet complete. Need to connect with mongo instead of firebase. The way you did in the code you shared is correct. Try to use this.subscribe instead of Meteor.subscribe. mwc subscribe will get stopped when you detach the element.

**Comment by dtodt** [comment]
@aruntk thanks for your advice.

I've changed the subscription target from **Meteor** to **this**, and it works well.
In adition, I was searching for the wrong subscription, the right was _"todo.list"_ insted of _"todo"_.
Because I'm not using the _"insecure"_ package anymore.

I've a doubt about when I can use **getMeteorData** or **tracker**.
This functions have their purpose, is there any wiki where I can find the MWC lifecycle?

Thanks.

**Comment by aruntk** [comment]
Both are similar except one difference. If you return and object in getMeteorData that object will be set as component property mwcData. Actually I wanted to deprecate getMeteorData in favour of tracker. Then I decided to keep it in case someone wants two tracker functions to separate reactive code. You can use any of the two.

**Comment by aruntk** [comment]
You can find this info in https://github.com/meteorwebcomponents/mixin.

**Comment by dtodt** [comment]
Thanks again, for the help.
