### ISSUE TITLE
TypeError: document.registerElement is not a function

### ISSUE THREAD

**Issue by brylie** [meteorwebcomponents/synthesis-meteor-polymer-npm-demo#2]
# Issue
On Firefox 49.0.2 (Ubuntu), the following error appears in console when rendering the demo:

```js
TypeError: document.registerElement is not a function
```

![screenshot_20161124_145306](https://cloud.githubusercontent.com/assets/17307/20599240/be32bd8e-b255-11e6-876c-9a745ca2f842.png)

# Solution
1. Go to `about:config`
2. filter the settings for `webcomponents`
3. set the value of `dom.webcomponents.enablded` to `true`

![screenshot_20161124_150131](https://cloud.githubusercontent.com/assets/17307/20599458/eb472de0-b256-11e6-8a33-4096b0f0e2f6.png)

**Comment by aruntk** [comment]
Another solution is to import webcomponents-lite polyfill.

**Comment by brylie** [comment]
OK, this should probably be documented, if it isn't already.
